baseURL = 'https://polishlessonsamsterdam.com'
# languageCode = 'en-US'
# title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

############

[[menus.what]]
name = 'whatever1'
pageRef = '/what'
weight = 1
params = { active = 1 }

[[menus.what]]
name = 'whatever2'
pageRef = '/what'
weight = 1
params = { active = 0 }

[[menus.what]]
name = "Section 1"
url = "#section1"
weight = 1
params = { active = 1 }

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


